
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatriceServerImplService", targetNamespace = "http://service.SOAP/", wsdlLocation = "http://192.168.1.111:9876/calculatrice?wsdl")
public class CalculatriceServerImplService
    extends Service
{

    private final static URL CALCULATRICESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATRICESERVERIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATRICESERVERIMPLSERVICE_QNAME = new QName("http://service.SOAP/", "CalculatriceServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.111:9876/calculatrice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATRICESERVERIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATRICESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public CalculatriceServerImplService() {
        super(__getWsdlLocation(), CALCULATRICESERVERIMPLSERVICE_QNAME);
    }

    public CalculatriceServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATRICESERVERIMPLSERVICE_QNAME, features);
    }

    public CalculatriceServerImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATRICESERVERIMPLSERVICE_QNAME);
    }

    public CalculatriceServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATRICESERVERIMPLSERVICE_QNAME, features);
    }

    public CalculatriceServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatriceServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatriceServer
     */
    @WebEndpoint(name = "CalculatriceServerImplPort")
    public CalculatriceServer getCalculatriceServerImplPort() {
        return super.getPort(new QName("http://service.SOAP/", "CalculatriceServerImplPort"), CalculatriceServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatriceServer
     */
    @WebEndpoint(name = "CalculatriceServerImplPort")
    public CalculatriceServer getCalculatriceServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.SOAP/", "CalculatriceServerImplPort"), CalculatriceServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATRICESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATRICESERVERIMPLSERVICE_EXCEPTION;
        }
        return CALCULATRICESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
