
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NonPositiveException", targetNamespace = "http://service.SOAP/")
public class NonPositiveException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NonPositiveException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NonPositiveException_Exception(String message, NonPositiveException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NonPositiveException_Exception(String message, NonPositiveException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.NonPositiveException
     */
    public NonPositiveException getFaultInfo() {
        return faultInfo;
    }

}
