
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ResultatNegatifException", targetNamespace = "http://service.SOAP/")
public class ResultatNegatifException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResultatNegatifException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResultatNegatifException_Exception(String message, ResultatNegatifException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ResultatNegatifException_Exception(String message, ResultatNegatifException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: client.ResultatNegatifException
     */
    public ResultatNegatifException getFaultInfo() {
        return faultInfo;
    }

}
